title: Julia Marks-Peterson Homepage
page-top-title: Julia Marks-Peterson
top-section-bg-text: Paleoclimate
home-subtitle: Julia Marks-Peterson
copyright-text: '&copy; Julia Marks-Peterson 2026. All Rights Reserved.'
